//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.SalesRecords = new HashSet<SalesRecord>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public double AddedSubtotal { get; set; }
        public int DiscountId { get; set; }
        public double GrandTotal { get; set; }
        public int DeliverymanId { get; set; }
        public bool DeliveryStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Deliveryman Deliveryman { get; set; }
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRecord> SalesRecords { get; set; }
    }
}
